### ISSUE TITLE
Deploing new-app in Openshift fails with an error: "must specify a user that is numeric and within the range of allowed users"

### ISSUE THREAD

**Issue by sturivny** [sclorg/nginx-container#119]
**Preconditions:**
Openshift version: oc v3.11.0+0cbc58b

**Steps:**
* login to the Openshift privileged.psi
* Create a new project
* Deploy a new app:oc new-app `nginx:1.16~https://github.com/sclorg/nginx-container.git --context-dir=1.16/test/test-app/ --strategy=source`

**Actual result:**
```
    Cloning "https://github.com/sclorg/nginx-container.git " ...
            Commit: fd6408c1fdaeb6777718c8354699583620bdabb8 (Run all tests and report results at the end (#117))
            Author: Petr Hracek <phracek@redhat.com>
            Date:   Mon Jul 27 13:24:40 2020 +0200
    error: build error: image "nginx@sha256:2963fc49cc50883ba9af25f977a9997ff9af06b45c12d968b7985dc1e9254e4b" must specify a user that is numeric and within the range of allowed users
Submit a correction or amendment below (click here to make a fresh posting)
```

**Expected result:**
The app was deployed without any errors

**Comment by sturivny** [comment]
Hello, any updates on this?

**Comment by hhorak** [comment]
@uhliarik Could you take a look at this, please, whether you see the same issue?

**Comment by hhorak** [comment]
I've looked at it and the exact command works for me. Are you still seeing the issue, @sturivny?

**Comment by sturivny** [comment]
@hhorak Looks like the root cause of this issue is in the cluster permissions.

**Comment by sturivny** [comment]
Thank you for investigating
