### ISSUE TITLE
alarming comment in Dockerfile questions safety of chmod use

### ISSUE THREAD

**Issue by mhrivnak** [sclorg/nginx-container#166]
A [comment in the Dockerfile](https://github.com/sclorg/nginx-container/blob/c7dda5b/1.20/Dockerfile.rhel8#L70) says ` # FIXME: Not sure if this is safe to do, just a hack to make the image work`. It then runs `chmod -R a+rwx /var/run`. That is all visible on the [Red Hat Container Catalog](https://catalog.redhat.com/software/containers/ubi8/nginx-120/6156abfac739c0a4123a86fd?container-tabs=dockerfile)'s Dockerfile display, where it is not confidence-inspiring.

**Comment by zmiklank** [comment]
Thanks for creating the issue.
Should be fixed in https://github.com/sclorg/nginx-container/pull/205.
