### ISSUE TITLE
Support for environment variable replacement in the S2I configuration files

### ISSUE THREAD

**Issue by wtrocki** [sclorg/nginx-container#18]
Currently s2i image allows to add static configuration files. Nginx by default is not providing any comprehensible solution to do it and usually best pattern to achieve that is to create wrapper script that would replace environment variables in the configuration.

Is that something that would be useful for this image? I would be happy to provide PR with the solution.

ping @hhorak @omron93 @mohammedzee1000

**Comment by notroj** [comment]
@wtrocki A PR would be great, yes please!

**Comment by phracek** [comment]
I guess, configuration files can be added into nginx-cfg directory. Seee https://github.com/sclorg/nginx-container/blob/master/1.24/s2i/bin/assemble#L17C9-L17C20

So closing this issues as this is not valid anymore.

Feel free to re-open it in case of missing feature.
