### ISSUE TITLE
update  ubi9/nginx120 to ubi9/122

### ISSUE THREAD

**Issue by msjatredhat** [sclorg/nginx-container#212]
Hello,
I have got a customer who requires nginx1.22 or higher to pass "External Penetration Testing".
Here is the Red Hat supported version of nginx.
https://catalog.redhat.com/software/containers/ubi9/nginx-120/61a609f2bfd4a5234d596287
Is there any road map to update the nginx to latest version ?

Regards
Selim 
Red Hat Brisbane Office

**Comment by phracek** [comment]
The newest image is already present in the Red Hat Catalog. So closing this issue.
