### ISSUE TITLE
The 121 and 122 .rhel8 docker files will not work

### ISSUE THREAD

**Issue by JaimeMagiera** [sclorg/nginx-container#214]
There are no ubi/xginx:122 and ubi/xginx:121 images available from Red Hat, thereby rendering the respective .rhel8 docker files incorrect. This is going to confuse developers. The builds will fail. Can those docker files be removed for the time being? Or maybe a note on the respective READMEs about this? I'm happy to contribute either way, if you let me know a preferred solution. 

The [latest available version from Red Hat is 120](https://catalog.redhat.com/software/containers/search?q=nginx&p=1&build_categories_list=Builder%20image).

**Comment by phracek** [comment]
I don't know if it was a typo from your side or not, but `ubi/xginx:122` really does not exist. In the upstream we have already 1.22 version but as you can see there is `.exclude-rhel8` file which means, that it is prepared but not yet build and even tested. Please be patient until Nginx1.22 is fully supported.

**Comment by phracek** [comment]
Version Nginx1.21 is not planned to be supported. As far as I know.
