### ISSUE TITLE
nginx 1.20 is missing USER in Dockerfile

### ISSUE THREAD

**Issue by jimmyjones2** [sclorg/nginx-container#231]
It's present in [1.18](https://github.com/sclorg/nginx-container/blob/master/1.18/Dockerfile.rhel8#L83) and [1.22](https://github.com/sclorg/nginx-container/blob/master/1.22/Dockerfile.rhel8#L83), but missing in [1.20](https://github.com/sclorg/nginx-container/blob/master/1.20/Dockerfile.rhel8#L83).

The result in the following failing:
```
podman run -it ubi8/nginx-120 /usr/libexec/s2i/run
2022/12/09 19:47:01 [emerg] 1#0: getpwnam("nginx") failed (2: No such file or directory)
nginx: [emerg] getpwnam("nginx") failed (2: No such file or directory)
```
or after running an s2i the resultant container runs as root (if not run in OpenShift):
```
s2i build empty registry.access.redhat.com/ubi8/nginx-120 nginx1
podman run -it nginx1 id
uid=0(root) gid=0(root) groups=0(root)
```

**Comment by zmiklank** [comment]
Thank you for creating the issue. I have created a [PR](https://github.com/sclorg/nginx-container/pull/232) that should fix this.
