### ISSUE TITLE
Uncomment VOLUME definition once Openshift Online is fixed

### ISSUE THREAD

**Issue by pkubatrh** [sclorg/nginx-container#43]
Creating an issue for this so that it is not forgotten.

For more information about the reason why it was commented out, see similar bug in httpd:
https://bugzilla.redhat.com/show_bug.cgi?id=1482143

Workaround introduced in:
https://github.com/sclorg/nginx-container/commit/5d1a17d27eb885e8b2480e6249af13a270129097

**Comment by phracek** [comment]
This is not valid any more for OpenShift 4 clusters.

We can use PVC by templates see https://github.com/sclorg/nginx-ex.

Adding VOLUMES does not make sense at all from OpenShift 4 cluster point of view.
