### ISSUE TITLE
access logging not going to stdout

### ISSUE THREAD

**Issue by dlbewley** [sclorg/nginx-container#53]
The [nginxconf.sd](https://github.com/sclorg/nginx-container/blob/master/1.12/root/opt/app-root/nginxconf.sed#L7) script is removing the access log line rather then redirecting logging to stdout like the error log.

Currently:

```
s%/var/opt/rh/rh-nginx112/log/nginx/error.log%stderr%
s%access_log  /var/opt/rh/rh-nginx112/log/nginx/access.log  main;%%
```

I would expect instead:

```
s%/var/opt/rh/rh-nginx112/log/nginx/error.log%stderr%
s%/var/opt/rh/rh-nginx112/log/nginx/access.log%stdout%
```

**Comment by gregswift** [comment]
Tried to make this work and found that the `access_log` match just doesnt do anything (at least i nthe 1.10 branch) because there is no `access_log` line for sed to match.

```$ cat nginx.conf | grep log
error_log stderr;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '```
```
here is the actual section of the log
```$ grep error_log -C1 nginx.conf
worker_processes auto;
error_log stderr;
pid /var/opt/rh/rh-nginx110/run/nginx/nginx.pid;```
