### ISSUE TITLE
Provide more documentation at docker hub

### ISSUE THREAD

**Issue by kbsingh** [sclorg/nginx-container#7]
https://hub.docker.com/r/centos/nginx-16-centos7/ has a few basic things about the container, but it would be good to extend that information to also include the default config already supplied inside the container and the default web content path's etc.

That would dramatically improve the usability of this container and reduce the amount of time the user needs to spend introspecting the container itself. 

If such information is available elsewhere, please link to it.

cc @kwk @hhorak

**Comment by wtrocki** [comment]
@kbsingh Repo Readme was updated recently with more information. Worth checking.
