### ISSUE TITLE
rhel8 s2i build uses wrong path in nginx.conf

### ISSUE THREAD

**Issue by paravz** [sclorg/nginx-container#82]
The instructions on https://access.redhat.com/containers/?tab=overview&get-method=red-hat-login#/registry.access.redhat.com/rhel8/nginx-114 using 1.14 produce a s2i container that doesn't start:
```
$ docker run --rm -it nginx-sample-app:latest
2019/05/07 21:52:37 [emerg] 1#0: open() "/etc/opt/rh/rh-nginx114/nginx/mime.types" failed (2: No such file or directory) in /etc/nginx/nginx.conf:28
nginx: [emerg] open() "/etc/opt/rh/rh-nginx114/nginx/mime.types" failed (2: No such file or directory) in /etc/nginx/nginx.conf:28
```

The paths in rhel8 have been changed, specifically mime.types:
```
$ docker run --rm -it nginx-sample-app:latest rpm -qf /etc/nginx/mime.types
nginx-1.14.1-8.module+el8+2505+fe936cef.x86_64
```

**Comment by hhorak** [comment]
I think having two config files for different distros in a common example app is not a good design. Let's try to find a better design in #83.
