### ISSUE TITLE
Support for streaming.

### ISSUE THREAD

**Issue by chainhead** [sclorg/nginx-container#95]
I would like to set-up nginx as a reverse proxy for TCP data using configuration as shown below.

```bash
stream {
    access_log /var/log/nginx/stream-rp.log ;
    error_log /var/log/nginx/stream-rp.err ;

    upstream messaging {
        server messaging:9090;
    }

    server {
        listen 9090;
        proxy_ssl false;
        location / {
            proxy_pass messaging;
        }
    }
}
```

This does not work since `stream` is not a known directive. The resolution is to add the stream modules dynamically as seen in `nginx -V` output below (`--with-stream=dynamic`).

```bash
nginx version: nginx/1.14.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/opt/rh/rh-nginx114/root/usr/share/nginx --sbin-path=/opt/rh/rh-nginx114/root/usr/sbin/nginx --modules-path=/opt/rh/rh-nginx114/root/usr/lib64/nginx/modules --conf-path=/etc/opt/rh/rh-nginx114/nginx/nginx.conf --error-log-path=/var/opt/rh/rh-nginx114/log/nginx/error.log --http-log-path=/var/opt/rh/rh-nginx114/log/nginx/access.log --http-client-body-temp-path=/var/opt/rh/rh-nginx114/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/opt/rh/rh-nginx114/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/opt/rh/rh-nginx114/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/opt/rh/rh-nginx114/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/opt/rh/rh-nginx114/lib/nginx/tmp/scgi --pid-path=/var/opt/rh/rh-nginx114/run/nginx/nginx.pid --lock-path=/var/opt/rh/rh-nginx114/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_v2_module --with-http_auth_request_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'
```

To load the module dynamically, I added this line right at the top of the`nginx.conf` file. The module path is derived from `--modules_path` in the `nginx -V` output.

```bash
load_module /opt/rh/rh-nginx114/root/usr/lib64/nginx/modules/ngx_stream_module.so
```

However, `/opt/rh/rh-nginx114/root/usr/lib64/nginx/modules` is empty.

Can you please suggest a way to enable the `stream` module?

**Comment by notroj** [comment]
This should be resolved in commit 910d124c2fc91c0ddf5bf6640e465f91611f29e9 for https://github.com/sclorg/nginx-container/pull/93 - thanks for the report

**Comment by chainhead** [comment]
> This should be resolved in commit [910d124](https://github.com/sclorg/nginx-container/commit/910d124c2fc91c0ddf5bf6640e465f91611f29e9) for #93 - thanks for the report

Isn't that only for `nginx-112`? I am interested in installing it as a container on OpenShift.

**Comment by notroj** [comment]
Yup we added mod_stream for all versions of the nginx container.

**Comment by chainhead** [comment]
umm....I logged into a pod running `rhscl/nginx-114-rhel7` and looked into `nginx -V`. There is `--with-stream=dynamic` and `opt/rh/rh-nginx114/root/usr/lib64/nginx/modules` is empty.

How do we enable streaming?

**Comment by notroj** [comment]
Sorry, I should have been clear - the updated image is not live yet.   If you're a RH customer you can file a support case and ask to track progress for the RHSCL containers via https://bugzilla.redhat.com/show_bug.cgi?id=1753002

**Comment by chainhead** [comment]
Since I am not a RH customer, when can I expect this to be available (if at all)?
