### ISSUE TITLE
Containers cannot be restarted

### ISSUE THREAD

**Issue by Richard-Degenne** [sclorg/nginx-container#96]
Hello,

I have encountered an issue which makes containers unable to restart once stopped.

This bug affects versions `1.10`, `1.12` and `1.14`.

# Steps to reproduce

- Build a minimal image.

```
mkdir s2i-nginx-bug
cd s2i-nginx-bug
s2i build . centos/nginx-112-centos7 s2i-nginx-bug:dev
```

- Create a container using the built image.

```
docker run -d --name s2i-nginx-bug s2i-nginx-bug:dev
```

- Observe that the container is up and running.

```
docker ps -a -f name=s2i-nginx-bug

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
72ebd4e6bc9e        s2i-nginx-bug:dev   "container-entrypoin…"   6 seconds ago       Up 5 seconds        8080/tcp, 8443/tcp   s2i-nginx-bug
```

- Restart the container.

```
docker restart s2i-nginx-bug
```

- Observe that the container crashed.

```
docker ps -a -f name=s2i-nginx-bug

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
72ebd4e6bc9e        s2i-nginx-bug:dev   "container-entrypoin…"   49 seconds ago      Exited (1) 4 seconds ago                       s2i-nginx-bug
```

# Notes

- Inspect the container's logs.

```
docker logs s2i-nginx-bug

/bin/ln: failed to create symbolic link '/var/opt/rh/rh-nginx112/log/nginx/access.log': File exists
```

The error is caused by [the logging feature in the `run` script][run]. The first time the container starts, the `ln` commands run just fine. However, when the container restarts, the targets already exist, resulting in the error shown above.

[run]: https://github.com/sclorg/nginx-container/blob/master/1.12/s2i/bin/run#L11-L14

## Suggested fix

Add the `-f` option to `ln` commands in order to force the recreation of the links.

```sh
if [ ! -v NGINX_LOG_TO_VOLUME -a -v NGINX_LOG_PATH ]; then
    /bin/ln -sf /dev/stdout ${NGINX_LOG_PATH}/access.log
    /bin/ln -sf /dev/stderr ${NGINX_LOG_PATH}/error.log
fi
```

Alternatively, you can check whether the targets already exist beforehand and skip the commands if they do.

## Workaround

Since `s2i` allows to override the `run` script given by the builder image, you can provide the suggested fix as part of the source files as `.s2i/bin/run`.

```sh
# In the `s2i-nginx-bug` folder

mkdir -p .s2i/bin && \
echo '#!/bin/bash

source /opt/app-root/etc/generate_container_user

set -e

source ${NGINX_CONTAINER_SCRIPTS_PATH}/common.sh

process_extending_files ${NGINX_APP_ROOT}/src/nginx-start ${NGINX_CONTAINER_SCRIPTS_PATH}/nginx-start
if [ ! -v NGINX_LOG_TO_VOLUME -a -v NGINX_LOG_PATH ]; then
    /bin/ln -sf /dev/stdout ${NGINX_LOG_PATH}/access.log
    /bin/ln -sf /dev/stderr ${NGINX_LOG_PATH}/error.log
fi

exec nginx -g "daemon off;"' > .s2i/bin/run && \
chmod +x .s2i/bin/run
```

You can then re-build the image and use it to work around the bug.

```
s2i build . centos/nginx-112-centos7 s2i-nginx-bug:dev
```

**Comment by hhorak** [comment]
@uhliarik Can you take a look at this, please?

**Comment by notroj** [comment]
Thanks for the report @Richard-Degenne.

Changing these to `test -e ${NGINX_LOG_PATH}/access.log || /bin/ln -sf ...` makes sense to me.

**Comment by EKoetsjarjan** [comment]
Hi I have the same issue on latest 1.16 image
I will try to implement this work around, but why is this issue still open. Are people not restarting the nginx containers?

**Comment by Partiks** [comment]
I am facing the same issue on nginx-120:1-21 image. For us, when we reboot the RHEL server after patching, it stays in the restarting section printing - ln: failed to create symbolic link '/var/log/nginx/access.log': File exists in nginx logs.

**Comment by Richard-Degenne** [comment]
Yeah, this issue has not been fixed as of yet. Maybe I'll send a PR if I can find some time.

**Comment by Richard-Degenne** [comment]
Strange that this never got fixed. I've submitted a PR. Easiest contribution of my life ;)

**Comment by phracek** [comment]
It has been already fixed by https://github.com/sclorg/nginx-container/pull/193
